# Generated by Django 5.2 on 2025-04-05 15:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du dossier')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('OP', 'Ouvert'), ('IP', 'En cours'), ('CL', 'Clôturé')], default='OP', max_length=2, verbose_name='Statut')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de création')),
                ('last_updated_date', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archivé')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='cabinet_management.client', verbose_name='Client Associé')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('status', models.CharField(choices=[('DRFT', 'Brouillon'), ('SENT', 'Envoyée'), ('PAID', 'Payée'), ('CANC', 'Annulée')], default='DRFT', max_length=4, verbose_name='Statut')),
                ('emailed_date', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi par email")),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='cabinet_management.case', verbose_name='Dossier Concerné')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lawyer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='lawyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to='cabinet_management.lawyer', verbose_name='Avocat Assigné'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_datetime', models.DateTimeField(verbose_name='Date et Heure du RDV')),
                ('status', models.CharField(choices=[('PEND', 'En attente'), ('CONF', 'Confirmé'), ('CANC', 'Annulé'), ('COMP', 'Terminé')], default='PEND', max_length=4, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de demande')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='cabinet_management.client', verbose_name='Client')),
                ('lawyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='cabinet_management.lawyer', verbose_name='Avocat')),
            ],
        ),
    ]
